# This is a sample YAML file for fault injection configuration
# The fields here should correspond to the Fields in fiConfig.py

# Deterministic fault seed for the injections
# Seed: 1000

# Type of fault to be injected for Scalars and Tensors
# Allowed values are {None, Rand, Zero, Rand-element, bitFlip-element, bitFlip-tensor, binaryBitFlip, sequentialBitFlip}

#ScalarFaultType: None
ScalarFaultType: bitFlip-element
TensorFaultType: bitFlip-element
#TensorFaultType: None

# Add the list of Operations and their probabilities here
# Each entry must be in a separate line ad start with a '-'
# each line must represent an OP and it's probability value
# See fiConfig.py for a full list of allowed OP values
# NOTE: These should not be any tabs anywhere below

Ops: 
# MAX-POOL = 1.0
  - CONV2D = 1.
  - ELU = 1.
  - BIASADD = 1.
  - RESHAPE = 1.
  - MATMUL = 1.
#  - ALL = 1.

#  - ALL = 1.
#  - SHAPE = 1.
#  - REALDIV = 1.
#  - ADD = 1.
#  - MUL = 1.
#  - FLOOR = 1.
# RELU = 1.0
# BIASADD = 1.0
# RESHAPE = 1.0
# MATMUL = 1.0
# - ALL = 1.0
 
# How many times the set of above operations should be skipped before injection
# SkipCount: 1

Instances:

  - CONV2D = 3 
  - ELU = 4
  - BIASADD = 5
  - RESHAPE = 1
  - MATMUL = 2

 # - SHAPE = 2
 # - REALDIV = 2
 # - ADD = 4
 # - MUL = 4
 # - FLOOR = 2



# There are three inject mode:
# There are 3 ways to determine HOW to select an operation for injection"
# 1) Using error rate to determine the probability of each opertaor to be injected " 
# 2) Profiling the instance of each operation so that each operation will be injected for ONCE only" 
# 3) Perform random injection over one op per run". In this mode, the 'ALL' variable in the Ops section must be claimed explicitly. 
# In the second and third mode, you'll need to specify the instances of all the operators in the algorithm

# Allowed values: 1) "errorRate"; 2) "dynamicInstance"; 3) "oneFaultPerRun" 
InjectMode: "oneFaultPerRun"
#InjectMode: "dynamicInstance"
#InjectMode: "errorRate"
